services:
  frontend:
    image: neuris/frontend
    volumes:
      - ./frontend/src/:/usr/src/app/src
    environment:
      - BACKEND_HOST=backend
    command: npm run dev -- --host
    ports:
      - 3000:3000
    networks:
      - dev
    depends_on:
      - backend
  backend:
    image: gradle:7-jdk17
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - SPRING_PROFILES_ACTIVE=local,compose
      - GH_PACKAGES_REPOSITORY_USER=${GH_PACKAGES_REPOSITORY_USER}
      - GH_PACKAGES_REPOSITORY_TOKEN=${GH_PACKAGES_REPOSITORY_TOKEN}
      - JAVA_OPTS=-XX:MaxDirectMemorySize=100M
    command: sh run.sh _start
    ports:
      - 8080:8080 # service
      - 5005:5005 # debugger
    networks:
      - dev
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=neuris
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
    ports:
      - 5432:5432
    networks:
      - dev
volumes:
  db-data:
networks:
  dev:
