openapi: 3.0.0
info:
  version: 0.0.1
  title: NeuRIS Normen Service API
  description: Interface for the normen service of the legal information system
  license:
    name: MIT
    url: https://mit-license.org

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/VICTORDELCAMPO_1/neu-ris_normen_service_api/0.0.1
  - url: https://ris.prod.ds4g.net/api/norms
    description: Public production server
  - url: http://localhost:3000
    description: Local development server

paths:
  /norms:
    get:
      summary: Get a list of all available norms
      operationId: listNorms
      responses:
        "200":
          description: Successful response with list of all norms
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        guid:
                          $ref: "#/components/schemas/Guid"
                        longTitle:
                          type: string
                example:
                  - guid: "86ee3aa7-b8ec-4f32-a6c7-2c7e13fc7919"
                    longTitle: "Gesetz über die Beschaffung sauberer Straßenfahrzeuge"
                  - guid: "07eb4f72-79cb-4070-93b5-62bfb44d3753"
                    longTitle: "Übereinkommen über das umweltgerechte Recycling von Schiffen"
        "400":
          description: ""

    post:
      summary: Create new norm
      operationId: createNorm
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NormWithoutGuid"
      responses:
        "201":
          description: Norm got successfully created
          headers:
            Location:
              description: URI reference for the new norm
              schema:
                type: string
        "400":
          description: Invalid norm

  /norms/{guid}:
    get:
      summary: Obtain a single norm by its Guid
      operationId: loadNorm
      parameters:
        - name: guid
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Guid"
      responses:
        "200":
          description: Norm was found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Norm"
        "404":
          description: No norm found for this Guid

    put:
      summary: Edit the frame data of a norm
      operationId: editNormFrame
      parameters:
        - name: guid
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/Guid"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MetadataFields"
      responses:
        "204":
          description: Norm was updated
        "400":
          description: ""

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    Guid:
      description: The globally unique identifier of the norm (format in UUID)
      type: string
      format: uuid
      example: "6a18380f-5c65-4f4d-902d-d49694f25de2"

    Date:
      description: The date format in XML files
      type: string
      pattern: '^[1-2]\d{3}-[0-1]\d-[0-3]\d$'
      example: "2020-10-21"

    ParagraphWithoutGuid:
      type: object
      required:
        - text
      properties:
        marker:
          type: string
          example: "(1)"
        text:
          type: string
          example: "Dieses Gesetz regelt Mindestziele und deren Sicherstellung bei der Beschaffung bestimmter Straßenfahrzeuge und Dienstleistungen, für die diese Straßenfahrzeuge eingesetzt werden, durch öffentliche Auftraggeber und Sektorenauftraggeber."

    ArticleWithoutGuid:
      type: object
      required:
        - marker
        - paragraphs
      properties:
        marker:
          type: string
          example: "§ 1"
        title:
          type: string
          example: "Allgemeiner Anwendungsbereich"
        paragraphs:
          type: array
          items:
            $ref: "#/components/schemas/ParagraphWithoutGuid"

    NormWithoutGuid:
      allOf:
        - $ref: "#/components/schemas/MetadataFields"
        - type: object
          required:
            - longTitle
            - articles
          properties:
            articles:
              type: array
              items:
                $ref: "#/components/schemas/ArticleWithoutGuid"

    Paragraph:
      allOf:
        - $ref: "#/components/schemas/ParagraphWithoutGuid"
        - type: object
          required:
            - guid
          properties:
            guid:
              $ref: "#/components/schemas/Guid"

    Article:
      allOf:
        - $ref: "#/components/schemas/ArticleWithoutGuid"
        - type: object
          required:
            - guid
          properties:
            guid:
              $ref: "#/components/schemas/Guid"
            paragraphs:
              type: array
              items:
                $ref: "#/components/schemas/Paragraph"

    Norm:
      allOf:
        - $ref: "#/components/schemas/NormWithoutGuid"
        - type: object
          required:
            - guid
          properties:
            guid:
              $ref: "#/components/schemas/Guid"
            articles:
              type: array
              items:
                $ref: "#/components/schemas/Article"

    MetadataFields:
      type: object
      properties:
        longTitle:
          type: string
          example: "Gesetz über die Beschaffung sauberer Straßenfahrzeuge"
        officialShortTitle:
          type: string
          example: "Saubere-Fahrzeuge-Beschaffungs-Gesetz"
        officialAbbreviation:
          type: string
          example: "SaubFahrzeugBeschG"
        referenceNumber:
          type: string
          example: "1 BvR 2011/94"
        publicationDate:
          $ref: "#/components/schemas/Date"
        announcementDate:
          $ref: "#/components/schemas/Date"
        citationDate:
          $ref: "#/components/schemas/Date"
        frameKeywords:
          type: string
          example: "BGBl I 2021, Nr 031;geltendes Bundesrecht;Umsetzung EG-Recht;Umsetzung EURL 2019/1161;Beschaffung;sauber;Straßenfahrzeug"
        authorEntity:
          type: string
          example: "DEU"
        authorDecidingBody:
          type: string
          example: "BT"
        authorIsResolutionMajority:
          type: boolean
          example: true
        leadJurisdiction:
          type: string
          example: "BMVI"
        leadUnit:
          type: string
          example: "G 22"
        participationType:
          type: string
          example: "EZ"
        participationInstitution:
          type: string
          example: "BR"
        documentTypeName:
          type: string
          example: "RV"
        documentNormCategory:
          type: string
          example: "XX"
        documentTemplateName:
          type: string
          example: "Template"
        subjectFna:
          type: string
          example: "FNA 703-12"
        subjectPreviousFna:
          type: string
          example: "FNA 703-11"
        subjectGesta:
          type: string
          example: "GESTA J040"
        subjectBgb3:
          type: string
          example: "BGB III 234"
        unofficialTitle:
          type: string
          example: "Nichtamtliche Langüberschrift"
        unofficialShortTitle:
          type: string
          example: "Nichtamtliche Kurzüberschrift"
        unofficialAbbreviation:
          type: string
          example: "Nichtamtliche Buchstabenabkürzung"
        risAbbreviation:
          type: string
          example: "SaubFahrzeugBeschG"

security:
  - BasicAuth: []
