otc:
  obs:
    bucket-name: neuris-document-storage-production

spring:
  data:
    redis:
      host: redis
      username: redis

sentry:
  environment: production
  traces-sample-rate: 0.01

neuris:
  document-numbers:
    bgh: KORE8****YYYY # results in e.g. KORE 8 0001 24
    bverfg: KVRE*****YY42 # results in e.g. KVRE 00001 24 42
    bverwg: WBRE60******* # TODO where put user und year?
    bsg: BSGRE0****YY
    # TODO: other docoffices
