otc:
  obs:
    bucket-name: neuris-document-storage-uat

spring:
  data:
    redis:
      host: redis
      username: redis

sentry:
  environment: uat
  traces-sample-rate: 0.01

neuris:
  environment: uat
  document-number-patterns:
    BGH: KORE7****1YYY
