error:
  nodes:
    active: false
info:
  git:
    enabled: true
    mode: full
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include: readinessState,redis,db
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

otc:
  obs:
    endpoint: https://obs.eu-de.otc.t-systems.com

sentry:
  exception-resolver-order: -2147483647

server:
  shutdown: graceful
  reactive:
    session:
      cookie:
        max-age: 43200 # 12*60*60
        http-only: false
#logging:
#  level:
#    org.springframework: DEBUG
spring:
  codec:
    max-in-memory-size: 100MB
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        registration:
          oidcclient:
            provider: keycloak
            scope:
              - openid
              - profile
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_CLIENT_ISSUER:}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

springdoc:
  api-docs:
    path: /api/docs.json
  swagger-ui:
    path: /api/docs.html

unleash:
  appName: unleash-proxy

neuris:
  document-number-patterns:
    BGH: KORE7****YYYY # results in e.g. KORE 7 0001 24
    BVerfG: KVRE*****YY41 # results in e.g. KVRE 00001 24 41
    BVerwG: WBRE61*****YY # TODO where put user und year?
    BSG: BSGRE1*****YY
    DS: DSRE*****YYYY
    CC-RIS: XXRE*******YY
    # TODO: other docoffices
