otc:
  obs:
    bucket-name: local
    ldml-bucket: local
local:
  file-storage: .local-storage
error:
  nodes:
    active: true
spring:
  data:
    redis:
      host: 127.0.0.1
      username: redis
      password: password
  security:
    oauth2:
      client:
        registration:
          oidcclient:
            client-id: ${OAUTH2_CLIENT_ID:}
            client-secret: ${OAUTH2_CLIENT_SECRET:}
        provider:
          keycloak:
            issuer-uri: ${OAUTH2_CLIENT_ISSUER:}
mail:
  exporter:
    response:
      mailbox:
        username: user@neuris.dev
        password: pa55word

database:
  seed: true
neuris:
  environment: staging
