on:
  workflow_call:
    inputs:
      browser:
        required: false
        type: string
        default: chromium
      mode:
        required: false
        type: string
        default: e2e
      runs:
        required: false
        type: string
        default: "1"
      subproject:
        required: false
        type: string
      workers:
        required: false
        type: string
    secrets:
      STAGING_URL:
        required: true
      SLACK_WEBHOOK_URL:
        required: false

jobs:
  playwright-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: ./frontend/package-lock.json
      - name: cache node modules
        id: cache-node
        uses: actions/cache@v4
        with:
          path: |
            ./frontend/node_modules
          key: modules-${{ hashFiles('./frontend/package-lock.json') }}
      - name: Install node modules
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: |
          npm ci
        working-directory: ./frontend
      - name: Get Playwright version
        working-directory: ./frontend
        run: echo "PLAYWRIGHT_VERSION=$(jq -r '.packages["node_modules/@playwright/test"].version' package-lock.json)" >> $GITHUB_ENV
      - name: Cache browser binaries
        id: cache-browser-binaries
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
      - name: Install playwright browsers
        if: steps.cache-browser-binaries.outputs.cache-hit != 'true'
        run: |
          npx --yes playwright install --with-deps ${{ inputs.browser }}
        working-directory: ./frontend
      - name: Run ${{ inputs.mode }} tests in ${{ inputs.browser }}
        env:
          E2E_BASE_URL: ${{ secrets.STAGING_URL }}
          E2E_TEST_USER: ${{ secrets.E2E_TEST_USER }}
          E2E_TEST_PASSWORD: ${{ secrets.E2E_TEST_PASSWORD }}
          E2E_TEST_USER_BGH: ${{ secrets.E2E_TEST_USER_BGH }}
          E2E_TEST_PASSWORD_BGH: ${{ secrets.E2E_TEST_PASSWORD_BGH }}
          E2E_TEST_BASIC_AUTH_USER: ${{ secrets.E2E_TEST_BASIC_AUTH_USER }}
          E2E_TEST_BASIC_AUTH_PASSWORD: ${{ secrets.E2E_TEST_BASIC_AUTH_PASSWORD }}
          GH_PACKAGES_REPOSITORY_USER: ${{ secrets.GH_PACKAGES_REPOSITORY_USER }}
          GH_PACKAGES_REPOSITORY_TOKEN: ${{ secrets.GH_PACKAGES_REPOSITORY_TOKEN }}
        run: |
          echo "Running ${{ inputs.mode }} ${{ inputs.subproject || '' }} tests ${{ inputs.runs }} times"

          test_target=${{ inputs.mode }}
          if [[ ${{ inputs.subproject || 'all' }} != 'all' ]]; then
            test_target=${{ inputs.mode }}:${{ inputs.subproject }}
          fi

          workers_config=""
          if [[ ${{ inputs.workers || 'default' }} != 'default' ]]; then
            workers_config="--workers=${{ inputs.workers }}"
          fi

          npm run test:"$test_target" -- --project ${{ inputs.browser }} --repeat-each ${{ inputs.runs}} $workers_config
        working-directory: ./frontend
      - name: Upload screenshots and traces of failed tests
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: failed-${{ inputs.mode }}-tests-${{ inputs.browser }}
          path: |
            ./frontend/test-results/**/*.png
            ./frontend/test-results/**/trace.zip
      - name: Send status to Slack
        # Third-party action, pin to commit SHA!
        # See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
        uses: digitalservicebund/notify-on-failure-gha@814d0c4b2ad6a3443e89c991f8657b10126510bf # v1.5.0
        if: ${{ failure() }}
        with:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
