on:
  workflow_call:

jobs:
  e2e-matrix:
    strategy:
      fail-fast: false
      matrix:
        project: [chromium, firefox, a11y]
    uses: ./.github/workflows/_playwright-test.yml
    with:
      project: ${{ matrix.project }}
    secrets: inherit
