on:
  workflow_call:

jobs:
  e2e-matrix:
    strategy:
      fail-fast: false
      matrix:
        subproject: [ caselaw, shared ]
        browser: [ chromium, firefox ]
        mode: [ e2e ]
        include:
          - mode: a11y
            browser: a11y
    uses: ./.github/workflows/_playwright-test.yml
    with:
      subproject: ${{ matrix.subproject}}
      browser: ${{ matrix.browser }}
      mode: ${{ matrix.mode }}
    secrets: inherit
