# Allows to run standalone Playwright based E2E/A11Y tests in particular browser,
# for debugging...
name: Manual Playwright test

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Playwright project"
        required: true
        type: choice
        options:
          - chromium
          - firefox
          - a11y
          - queries
      runs:
        description: "Number of subsequent runs"
        required: false
        type: string
        default: "1"
  schedule:
    - cron:  '00 6 * * *'

jobs:
  playwright-test:
    uses: ./.github/workflows/_playwright-test.yml
    with:
      project: ${{ inputs.project || 'chromium' }}
      runs: ${{ inputs.runs || '1' }}
    secrets: inherit
