# Allows to run standalone Playwright based E2E/A11Y tests in particular browser,
# for debugging...
name: Manual Playwright test

on:
  workflow_dispatch:
    inputs:
      browser:
        description: "Playwright browser engine"
        required: true
        type: choice
        options:
          - chromium
          - firefox
      mode:
        description: "Type of tests"
        required: true
        type: choice
        options:
          - e2e
          - a11y
      subproject:
        description: "Subproject"
        required: false
        type: choice
        options:
          - caselaw
          - all
      runs:
        description: "Number of subsequent runs"
        required: false
        type: string
        default: "1"
  schedule:
    - cron:  '00 6 * * *'

jobs:
  playwright-test:
    uses: ./.github/workflows/_playwright-test.yml
    with:
      browser: ${{ inputs.browser || 'chromium' }}
      mode: ${{ inputs.mode || 'e2e' }}
      runs: ${{ inputs.runs || '1' }}
      subproject: ${{ inputs.subproject }}
    secrets: inherit
